### ISSUE TITLE
encoding needed for item-description elements

### ISSUE THREAD

**Issue by iKL3W** [EthanStandel/browser-rss-parser#4]
Some item-description elements contain html like <p> and l&#039. Is there a way to use encoding for item-description??

Thanks

**Comment by EthanStandel** [comment]
So... I think this shouldn't be happening anymore since I added this line. Are you sure it's still happening?

https://github.com/EthanStandel/browser-rss-parser/blob/main/src/components/RssContent.tsx#L163

**Comment by iKL3W** [comment]
![image](https://user-images.githubusercontent.com/75533129/156899820-b12f97de-bd84-4df9-9f8c-8fabe356d023.png)
still happening for titles only from the 'Numerama' source

![image](https://user-images.githubusercontent.com/75533129/156899842-a982dcbf-2ba9-44af-9859-d33d115105e9.png)
and happening for item-description from 'France 3' and other sources

**Comment by EthanStandel** [comment]
Ah... it's double encoded because it's in HTML in XML... fix coming soon
